OPENAI_API_KEY = "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"
SUPABASE_URL = "https://embmafaufiiuzwfosdfk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtYm1hZmF1ZmlpdXp3Zm9zZGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTI0MTUsImV4cCI6MjA3MTM2ODQxNX0.g4QG3cMsSjs1tvwRTQtSAUTXlio8yRt6FqbO9lXut1o"
